server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

my:
  nickname: DEV USER!!
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6